### ISSUE TITLE
酒蔵情報に備考欄が欲しい

### ISSUE THREAD

**Issue by y2naranja** [Code-for-SAKE/Sakepedia-Nuxt#100]
- 要件<br>酒蔵見学ツアーや関連施設がある場合などの付随情報を入力する欄が欲しい
- 解決案<br>備考欄を作って登録可能にする
- 懸案事項<br>備考欄の情報はどこまで詳しく載せるか

**Comment by cgetc** [comment]
以下の項目を追加
- 見学情報
- 試飲
- カフェ併設
- ショップ併設
- その他のお酒を作っているか
