### ISSUE TITLE
酒蔵情報にFAX欄が欲しい

### ISSUE THREAD

**Issue by y2naranja** [Code-for-SAKE/Sakepedia-Nuxt#107]
- 電話かFAXでしか販売を受け付けていない蔵があることから、FAX番号もあった方がよい
- 現在の酒蔵登録画面の入力項目、電話番号の下あたりに項目を追加するとグッド

**Comment by erikka-22** [comment]
こちら対応します！

**Comment by nichesuch** [comment]
お願いします！
