### ISSUE TITLE
酒蔵追加ページの「追加」ボタンが動作しない．

### ISSUE THREAD

**Issue by erikka-22** [Code-for-SAKE/Sakepedia-Nuxt#108]
酒蔵追加ページで，入力必須の「名前」のみ入力して「追加」ボタンをクリックしても，画面が変化せず，データの登録も行われません．

**Comment by y2naranja** [comment]
#97と関連する内容かと思われます。
多分住所か緯度経度が必須項目なのですが（地図上の座標に使用するため）、エラーメッセージなしで何も起こらなくなってしまいます。
なので、
- 必須入力項目にはラベルでその旨を表記
- 追加・更新時に必須項目もれのエラーメッセージを出す
が必要になります。

**Comment by y2naranja** [comment]
もしくは、
- 緯度経度を求めようとしてできず、エラーメッセージを出さずに静かにコケている
も考えられます。
なので、まず検討すべきは住所を必須入力項目にするかどうか、ですね。

**Comment by nichesuch** [comment]
緯度経度を求めようとしてできず、エラーメッセージを出さずに静かにコケている
だったので、住所がない時は緯度経度を求めないようにしました。

**Comment by nichesuch** [comment]
#109 で対応しました。
