### ISSUE TITLE
酒蔵の編集時に創業年が表示されない

### ISSUE THREAD

**Issue by mryosuke** [Code-for-SAKE/Sakepedia-Nuxt#114]
酒蔵の情報を編集する際、既に入力されているデータに関しては編集画面のテキストボックスに表示されるかと思います。
しかし創業年については、入力されているデータが表示されず空欄になります。（例：マスカガミ）

**Comment by nichesuch** [comment]
これはデータに「年」が入っていたからでした。
数値で上書きしたので、以後は表示されるようになります。
