### ISSUE TITLE
特定の酒蔵が登録できない

### ISSUE THREAD

**Issue by mryosuke** [Code-for-SAKE/Sakepedia-Nuxt#121]
新潟県の樋木酒造(A590)が登録出来ません。

**Comment by y2naranja** [comment]
こちら、私もやってみましたが登録ができません。
スプレッドシートの住所に「西区」が抜けていたため、住所を「新潟県新潟市西区内野町582」にしてみましたが変化なし。
※ぐぐると出てくる内野町577は古いデータです

9/25のHackDayではデータ登録とサニタイズを優先して、後ほど条件を変えてやってみます。

**Comment by nichesuch** [comment]
もろもろ修正、改善して、登録できました。
このissueはクローズさせていただきます。
