### ISSUE TITLE
酒蔵の詳細ページに項目名をつける

### ISSUE THREAD

**Issue by nichesuch** [Code-for-SAKE/Sakepedia-Nuxt#134]
項目名がないから、どれがなんだかわかりにくい。
<img width="426" alt="スクリーンショット 2021-09-27 23 19 56" src="https://user-images.githubusercontent.com/2096703/134926935-a33a85e7-35ab-4291-8a25-466599b55a73.png">

日本酒データなどには項目名がある。
<img width="531" alt="スクリーンショット 2021-09-27 23 20 28" src="https://user-images.githubusercontent.com/2096703/134927020-627f6511-944f-45cd-b3b3-11e13750f3a4.png">

**Comment by nichesuch** [comment]
廃業年だけは、入っていなかったらラベルも表示しないようにしましょう。

**Comment by shinjima2** [comment]
創業年（たぶん廃業年も）の末尾に"年"がなくわかりにくいので、項目名と同様、修正した方が良いです。
”〇〇〇〇年”と入力された過去データは再編集しない限り、”〇〇〇〇年”と表示されます。

**Comment by shinjima2** [comment]
このIssueお手頃だなと思ったら改修済みでした。クローズですね

**Comment by nichesuch** [comment]
そうですね。closeします。
