### ISSUE TITLE
データ更新日時、更新者をDBに追加

### ISSUE THREAD

**Issue by shinjima2** [Code-for-SAKE/Sakepedia-Nuxt#140]
酒蔵データ”breweries"などのデータレコード（ドキュメント）にデータ更新日時（できれば更新者も）を追加。
現状、apiで取得できるデータには追加や更新に関わる情報として”author”フィールドしかないよう。

データ更新（棚卸し）作業時に、更新作業の進捗確認や更新作業の対象を絞り込む時の参考となる。

**Comment by nichesuch** [comment]
@shinjima2 対応しました。
api、画面で、更新日時を確認できるようにしました。
ただし、今後の更新のみになります。

**Comment by nichesuch** [comment]
更新日時でのソートも欲しいですかね。

**Comment by shinjima2** [comment]
ありがとうございます！
今ちょうど都道府県検索追加のソースコードを勉強してました笑
