### ISSUE TITLE
銘柄にふりがなを付記できるようにする

### ISSUE THREAD

**Issue by shinjima2** [Code-for-SAKE/Sakepedia-Nuxt#142]
読み方が難しい銘柄が多いので、銘柄のふりがながあると良いですね。
ただ、既存のデータに追加していくのは大変ですが。。

**Comment by shinjima2** [comment]
銘柄に加えて日本酒の方も一緒にソース修正終わりました。
が、ローカル環境で銘柄も日本酒も詳細画面がエラーとなるので、それが解決してソース修正に問題ないか確認できたらプルリクします

**Comment by shinjima2** [comment]
プルリクさせてもらいました。
ローカルでテストしたサンプルスクショ添付します。
<img width="183" alt="スクリーンショット 2022-08-06 14 39 45" src="https://user-images.githubusercontent.com/76687689/183237552-85e88f44-5cc1-41f4-8359-c438ecc6862f.png">
<img width="181" alt="スクリーンショット 2022-08-06 14 39 34" src="https://user-images.githubusercontent.com/76687689/183237558-7985767a-b04b-49bd-99c9-57dc00a9741c.png">

**Comment by nichesuch** [comment]
@shinjima2 ありがとうございました！
