### ISSUE TITLE
ログインしていない状態だと開けない酒蔵ページがある

### ISSUE THREAD

**Issue by JQinglong** [Code-for-SAKE/Sakepedia-Nuxt#148]
例えば、「いそのさわ」（福岡県）は、ログインしていない状態で開こうとすると、
Request failed with status code 401
のエラーページになる。
ログインしている状態ならば、開くことができる。

**Comment by nichesuch** [comment]
保存するデータをauthorからuserIdに移行していて、authorがない場合、userIdから名前を検索しようとしていました。
`/users/:id/name`のgetはログインしていなくても許可しないといけない模様です。
また、最終的にuserIdの方を使いたいので、userIdを先に確認したいです。

**Comment by nichesuch** [comment]
@JQinglong 遅くなりました！マージして反映しました！ありがとうございました！
