### ISSUE TITLE
異なる酒蔵で同一の銘柄があると登録できない？

### ISSUE THREAD

**Issue by okadatsuneo** [Code-for-SAKE/Sakepedia-Nuxt#155]
初めまして。本日こちらの存在を知り、少し登録・更新してみたところです。

表題の件ですが、銘柄は1つしか登録できないのでしょうか？

具体的には鹿児島県西酒造の「天賦」を登録しようとすると、
岡山県三光正宗の「天賦」という銘柄がすでに登録されているために
「すでに存在します」とのメッセージが出て、銘柄登録できません。

改善できればありがたいです。

**Comment by nichesuch** [comment]
コントリビュートありがとうございます！🍶

確かに現在は銘柄の名前だけでユニークチェックをしているので、登録できなさそうです！

酒蔵+銘柄で一つになるようにユニークチェックをかける方向で検討させていただきます！

**Comment by nichesuch** [comment]
@okadatsuneo 対応しました！
ご連絡ありがとうございました！

**Comment by okadatsuneo** [comment]
西酒造の「天賦」を登録できました。
早々の改善ありがとうございました。
