### ISSUE TITLE
「併設カフェ」の項目が「試飲」の入力内容と同じになる。

### ISSUE THREAD

**Issue by okadatsuneo** [Code-for-SAKE/Sakepedia-Nuxt#156]
酒蔵の情報更新のページで「試飲」「併設カフェ」などをチェックする欄があり、そこをチェックすると営業時間などを入力する欄が出てきますが、
「試飲」「併設カフェ」「併設ショップ」の3つをチェックした時に、
「試飲」と「併設カフェ」で異なる内容を入力しても、更新ボタンを押した後の情報が、
「併設カフェ」の欄の内容が「試飲」の欄で入力したものと同じになってしまいます。
「併設ショップ」の入力欄に入力したものは他の欄に影響受けずに登録できています。

鹿児島県濱田酒造の情報更新をしていて、そのような状態になりました。

**Comment by nichesuch** [comment]
api側がよろしくなさそうです！報告ありがとうございます！
おそらく本日のソーシャルハックデーで改修できると思われます！

**Comment by nichesuch** [comment]
@okadatsuneo こちらも対応しました！ご確認と再登録お願いします！

**Comment by okadatsuneo** [comment]
鹿児島県濱田酒造について、それぞれの情報を登録できました。
改善ありがとうございました。
