### ISSUE TITLE
酒蔵の編集ページでメールアドレスの削除ができない

### ISSUE THREAD

**Issue by okadatsuneo** [Code-for-SAKE/Sakepedia-Nuxt#162]
酒蔵のページですでにメールアドレスが入っている会社で、現在webサイトを見るとメールアドレスの記載がないので、
メールアドレスをデータベースから削除しようと思います。
しかしメールアドレスの欄に「@」の文字が入っていないとエラーにしているようなので、削除できません。

具体的には徳島県の本家松浦酒造場さんで、元々メールアドレスが登録されていた。これを削除したい。
1.半角スペースにする→メールアドレスは削除されない
↓
2.「n/a」と入力する→「@がないので登録できない」みたいなエラーが出る
↓
3.無理矢理「n/a@n」でひとまず登録しています。

**Comment by nichesuch** [comment]
#165 と同様の現象かと思われます。

空白の場合はその項目を更新しないようにしている処理が入っていて、削除ができなくなっています。

**Comment by nichesuch** [comment]
パラメータの存在チェックを入れる。
存在したら、空白でも更新。
存在しなかったら、その項目は更新しないようにする。
