### ISSUE TITLE
日本酒更新/銘柄更新のページで酒蔵・銘柄の選択が1回でできない

### ISSUE THREAD

**Issue by okadatsuneo** [Code-for-SAKE/Sakepedia-Nuxt#163]
日本酒更新/銘柄更新のページで、酒蔵や銘柄を入力する際、
該当の名称を入力して一致するものが選択肢として表示されてそれを選択しますが、
1回選択しただけでは入力されません。
入力欄の▼を押して、その下に出てくる選択肢をもう1回選択すると、それが入力欄に表示されます。

文章だけだとわかりにくいかもしれませんが。。

**Comment by nichesuch** [comment]
@okadatsuneo わかります。

直そうとしたのですが、ちょっとうまく行っていません。

酒蔵のページにある`銘柄追加`ボタンや
銘柄のページにある`日本酒追加`ボタンでは
事前に入力された状態で表示されるので、
現状ではそちらから入力するのがオススメです。

**Comment by okadatsuneo** [comment]
新規登録の場合はすでに入力された状態で表示されているので問題ないのですが、
既登録の日本酒/銘柄データで銘柄・蔵元が未登録のものに、それらの情報を追加しようと
すると少し手間がかかる感じです。

直し方が見つかるといいですね。
