### ISSUE TITLE
銘柄の項目修正が反映されない

### ISSUE THREAD

**Issue by iamakawa** [Code-for-SAKE/Sakepedia-Nuxt#165]
・Windows10/Google Chrome
・銘柄を登録した際、不要な項目を削除して反映しても、値が反映されない
・空白の場合は処理を行わないような設定になっている？

**Comment by iamakawa** [comment]
![Sakepedia-Nuxt-Google-Chrome-2022-05-02-22-29-13](https://user-images.githubusercontent.com/15156125/166242514-e0fba3d1-ce87-4926-aeaf-434a671c3625.gif)

**Comment by nichesuch** [comment]
> ・空白の場合は処理を行わないような設定になっている？

正解でした。
その方が良いような気もするし、修正した方が良いような気もしますね。

**Comment by iamakawa** [comment]
そうなんですよね、これをやろうとすると、全項目に対して一致確認をしなきゃいけないので大分処理が面倒になりそうな気が・・。
