### ISSUE TITLE
日本酒醸造データ詳細ページからのリンク

### ISSUE THREAD

**Issue by okadatsuneo** [Code-for-SAKE/Sakepedia-Nuxt#168]
各日本酒醸造データの詳細ページからのリンクは[一覧に戻る]ボタンで日本酒醸造データ一覧ページに戻るしかないですが、
該当の「日本酒」「銘柄」「酒蔵」などに行けるようなリンクがあると便利かなと思います。

(日本酒詳細ページに酒蔵、銘柄のリンクがあるように)

**Comment by nichesuch** [comment]
確かにそうですね！改善しておきます！

**Comment by nichesuch** [comment]
対応しました！

**Comment by okadatsuneo** [comment]
醸造データのタイトルをクリックすると日本酒詳細ページに遷移できるようになりました。

早々にご対応いただきありがとうございました。
