### ISSUE TITLE
jestのActionsが動作していない

### ISSUE THREAD

**Issue by nichesuch** [Code-for-SAKE/Sakepedia-Nuxt#18]
jestが動く前の以下でエラーになっている。
actions/checkout@v1

何か権限周りかもしれない。

**Comment by ao-spirogyra** [comment]
memo:
`Git fetch failed with exit code 128` と言われていてググってみると
https://stackoverflow.com/questions/51547858/vsts-git-fetch-failed-with-exit-code-128#:~:text=Another%20possible%20cause%20of%20the,the%20process%22%20solution%20for%20us.

> Another possible cause of the "Git fetch failed with exit code: 128" error message - it happened to us for pull requests builds when a developer clicked merge right after a pull request was created and the build, of course, hasn't finished yet.
So it was the "follow the process" solution for us.

と言われている
