### ISSUE TITLE
sakepedia.code4sake.org にアクセスできなくなりました。

### ISSUE THREAD

**Issue by okadatsuneo** [Code-for-SAKE/Sakepedia-Nuxt#182]
久々にhttps://sakepedia.code4sake.org/ にアクセスしたところ、
アクセスできなくなりました。
具体的には、
https://sakepedia.code4sake.org/
をブラウザで開こうとすると、httpsのセキュリティの警告画面になり、
詳細設定からセキュリティなしで無理矢理接続しようとすると、
添付のようなServer Errorになりました。

WindowsでGoogle ChromeでもMicrosoft Edgeでも同様でした。
![image](https://user-images.githubusercontent.com/57310969/179219850-d1b7c52b-5983-45b3-a1cd-92b6b4453892.png)

**Comment by y2naranja** [comment]
Android12/Firefoxでも現象確認しました。

**Comment by nichesuch** [comment]
なんと！ご報告ありがとうございます！
家に戻ったら確認します！

**Comment by nichesuch** [comment]
@okadatsuneo 
遅くなりましたが、正常動作するようになりました。
SSL証明書の自動更新がエラーで止まってしまっていて、再稼働させる際に、色々ミスしてしまって時間がかかりました。
ご迷惑おかけしました。

**Comment by okadatsuneo** [comment]
早々にご対応ありがとうございました。
無事アクセスできました。
