### ISSUE TITLE
登録していない人がGithubシングルサインオンできない

### ISSUE THREAD

**Issue by tadanet3** [Code-for-SAKE/Sakepedia-Nuxt#190]
一部の環境でGithubシングルサインオンに失敗する。
callback. Please Wait
と表示されて、その状態から先に進まない。
![image](https://user-images.githubusercontent.com/1810398/191307195-f9550752-441c-4d17-a54e-5f0862dc8783.png)

GithubにはSakepedia Nuxtが追加されている。
![image](https://user-images.githubusercontent.com/1810398/191307868-40330a89-8c6a-4fcb-b77d-ded2c999a6b1.png)

デベロッパーツールで確認してみると、callback?code=*******時に401エラーが発生している。
「サーバーからの応答に時間がかかっています。(786 ms)推奨される限界値は500msです。」
と出てるのが関係しているかも。
![image](https://user-images.githubusercontent.com/1810398/191309978-75683c93-b931-4d51-8f00-5a926242e761.png)

**Comment by tadanet3** [comment]
GithutのSakepedia Nuxtを一旦Revokeしたり
OSとブラウザを色々変えて（Ubuntu, Windows, Android, Firefox, Edge, Chrome）試してみましたが、解決しませんでした。

**Comment by kaizumaki** [comment]
ここ↓は、b-buttonのイベントにmethodsを割り当てるべきでは...？

https://github.com/Code-for-SAKE/Sakepedia-Nuxt/blob/b456fa77ec031a40afbce54e550eed96605c0ed9/pages/auth/login.vue#L15

**Comment by nichesuch** [comment]
ありがとうございます！

@click="githublogin"
だと、CORSエラーになります！

**Comment by nichesuch** [comment]
envファイルが読み込めてない可能性がありそうなので、そこを確認中です。

**Comment by kaizumaki** [comment]
> @click="githublogin" だと、CORSエラーになります！

なるほど。とするとプロキシ？
StackOverflowで、似たような質問があがっています。
https://stackoverflow.com/questions/42150075/cors-issue-on-github-oauth

**Comment by kaizumaki** [comment]
githubloginのmethodsって、使ってないんですよね？ただ `/api/auth/login` に遷移しているだけだと、promise的なところでうまくいかないような気がします。

**Comment by kaizumaki** [comment]
あ、じゃなくて、むしろcallbackがうまくいっていないのか。

**Comment by nichesuch** [comment]
/api/auth/login
↓
api/route/auth.js内でpassport.authenticate('github')なのでgithubのログインが走る
↓
/page/callback.vue　ここでplease wait
↓
/api/auth/callback
ここで401

**Comment by nichesuch** [comment]
うまくいくと
/api/auth/callback　でuser情報もらって
↓
$storeにuser情報入れて
/auth/account
に遷移してます。

**Comment by kaizumaki** [comment]
> /api/auth/callback
> ここで401

ここ↑で「Unauthorized」になるので、やっぱり何かしらのpromise的なやりとりがうまくいっていないんでしょうね。

**Comment by kaizumaki** [comment]
これは参考になるかな？
https://github.com/jaredhanson/passport-github/issues/3#issuecomment-5608296

**Comment by nichesuch** [comment]
GitHub側のOAuth Appsの設定では以下になっています。
https://sakepedia.code4sake.org/callback

**Comment by nichesuch** [comment]
`router.get`は、設定で、getしているわけではないはず。

`/api/auth/callback`をここで処理しますよ。
の意味だったと思います。

**Comment by nichesuch** [comment]
だいたい以下と同じことをしているはず。
https://qiita.com/reireias/items/2bc1b33dfb0e63f31517

**Comment by nichesuch** [comment]
StrategyにcallbackURLが設定されてないのが原因かも！

**Comment by nichesuch** [comment]
User作る時に、unique設定されているnameがないのが原因でした。
結構前からこの状態なので、なぜ今まで動いていたのか。。。

**Comment by nichesuch** [comment]
本番環境は手修正済み。
整理してからPR出す予定。

**Comment by tadanet3** [comment]
Githubシングルサインオンできる事を確認しました。
