### ISSUE TITLE
日本酒ページからリンクへ飛ぶ時別タブ表示にする

### ISSUE THREAD

**Issue by mamisada** [Code-for-SAKE/Sakepedia-Nuxt#195]
https://sakepedia.code4sake.org/sakes/ の先の詳細欄からURLへ飛ぶと、タブのURLそのものが変わってしまうので、別タブ表示で元のSakepediaページが残るようにしておく（行ったままでなく中のページに戻ってきやすいように）

**Comment by nichesuch** [comment]
これ対応します。

**Comment by nichesuch** [comment]
@mamisada 修正できました！
