### ISSUE TITLE
「温泉近くの酒蔵」Mapで、酒蔵を選択したときに、酒蔵情報へのリンクになっていない。

### ISSUE THREAD

**Issue by JQinglong** [Code-for-SAKE/Sakepedia-Nuxt#203]
「都道府県別の酒蔵」Mapでは酒蔵を選択すると、表示されるポップアップの酒蔵名が、酒蔵情報へのリンクになっている。
「温泉近くの酒蔵」Mapでも同様に酒蔵情報へのリンクにしたい。
![image](https://user-images.githubusercontent.com/11361028/221340409-264efb37-d6a3-49d9-a545-cf89a3df7f92.png)

**Comment by nichesuch** [comment]
リリースされました 🎉
