### ISSUE TITLE
検索して各詳細ページを開いたあとブラウザバックで検索結果に戻りたい

### ISSUE THREAD

**Issue by ao-spirogyra** [Code-for-SAKE/Sakepedia-Nuxt#46]
検索結果の各ページを開いた後、ブラウザバックすると検索がリセットされてしまう
検索をリセットせずにそのまま戻れると便利だしそうしないと5ページ目とかを見てた場合は不便

**Comment by ao-spirogyra** [comment]
たぶんreplacestateを使えば簡単にできる

**Comment by nichesuch** [comment]
これはぜひお願いします！
