### ISSUE TITLE
eslintを導入したい

### ISSUE THREAD

**Issue by ao-spirogyra** [Code-for-SAKE/Sakepedia-Nuxt#49]
このままだと2人+α種類の書き方が混在することになってしまいかねないのでeslintを導入したい

**Comment by nichesuch** [comment]
やりましょう！

**Comment by nichesuch** [comment]
参考
https://www.soudegesu.com/post/javascript/format-nuxt-typescript-on-save/

eslintとPrettierを入れて、どこかのタイミングでがさっと入れ替えます。

**Comment by nichesuch** [comment]
@ao-spirogyra 何か作業されていたりしますか？
eslint導入したので、フォーマット修正をしてしまおうと思います。

途中のものがあればそのPRを待ってからやらないとコンフリクト地獄になるのでおっしゃってください。

**Comment by ao-spirogyra** [comment]
していますが長引きそうなので大丈夫です！

**Comment by nichesuch** [comment]
了解しました。ではがさっと修正してしまいます。

**Comment by nichesuch** [comment]
@ao-spirogyra 遅くなりましたが、マージしました。
一つやり切れていないですが、どう直せばいいかよくわからず。。。

**Comment by ao-spirogyra** [comment]
調べると https://github.com/nuxt/nuxt.js/issues/5218 が出てきて読んだ感じだと`.eslintrc.js`に`'nuxt/no-cjs-in-config': 'off',`を追加して解決しているのでそれでよさそうです
