### ISSUE TITLE
法人番号の登録

### ISSUE THREAD

**Issue by ocean3fish** [Code-for-SAKE/Sakepedia-Nuxt#66]
- 法人番号も紐付けられるとデータの利用用途が広がりそうです
- ユーザが登録できるようにしても良いかも

**Comment by nichesuch** [comment]
アイディアありがとうございます。
一応あります。

<img width="247" alt="スクリーンショット 2021-04-21 23 27 17" src="https://user-images.githubusercontent.com/2096703/115570344-0044d700-a2f9-11eb-93ff-02ad3ff3510d.png">

法人番号だけでよいのかわからなかったのでetcとしてしまっていて、あまりデータが入っていない状態です。
一つの法人で酒蔵2つ持っているところはあったような気はします。

**Comment by ocean3fish** [comment]
あったんですね！ありがとうございます。
1つのフォームに複数の種類のデータが混ざってくると処理がややこしくなると思いますので、

法人番号（国税庁が指定する13桁の識別番号）

と明確化しておくのをオススメしたいところです。

**Comment by nichesuch** [comment]
ですよね。
最初は`自動採番ではない一意の値がほしいね`って話になって、`法人番号`に行きつき、でも先の問題に気づき、etcとしてしまった経緯です。
そして結局自動採番してるので、一意性も気にすることないので、この項目はご提案の通り明確にします。

法人番号（国税庁が指定する13桁の識別番号）
