### ISSUE TITLE
酒蔵ページのURLやメールアドレスにハイパーリンク化する

### ISSUE THREAD

**Issue by gurosumodulor** [Code-for-SAKE/Sakepedia-Nuxt#71]
酒蔵ページのURLやメールアドレスがテキスト表示されていますが、ハイパーリンクにはなっていないため、ハイパーリンクにして頂けると便利に使用できると思います。
例
https://sakepedia.code4sake.org/breweries/60638e8e8d83689315fb5d84

**Comment by erikka-22** [comment]
こちら担当します！
