### ISSUE TITLE
酒蔵マップのビジュアライズを検討

### ISSUE THREAD

**Issue by nichesuch** [Code-for-SAKE/Sakepedia-Nuxt#87]
現状、雑多にピンが立っているので、何かしら意味合いを持たせたい。

**Comment by nichesuch** [comment]
![image](https://user-images.githubusercontent.com/2096703/118477290-7cd8a300-b749-11eb-8550-fd563b905586.png)

**Comment by r-soga** [comment]
- 僕も、ピンを何かしらの観点でグルーピングできればなと思います。
- 例
  - 付近の河川で整理する：四万十川とか？
    - ![image](https://user-images.githubusercontent.com/55010847/119212354-b49d6d00-baf2-11eb-854e-f627d9e8b8d5.png)
  - 県ごとに整理する
  - 味など日本酒の属性で整理する

**Comment by r-soga** [comment]
- 現在地に近い酒蔵のみ表示する
- 作っていない酒蔵もある

**Comment by nichesuch** [comment]
ひとまず県ごとでグルーピングした。
