### ISSUE TITLE
トップページで、温泉地付近の酒蔵を表示する

### ISSUE THREAD

**Issue by r-soga** [Code-for-SAKE/Sakepedia-Nuxt#89]
## ToDoリスト

- [x] 温泉地の緯度・経度を取得し、DBへ保存する→jsonから読み出す。
  - [温泉地一覧](http://ja.dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fja.dbpedia.org&query=%23PREFIX+dbpj%3A+%3Chttp%3A%2F%2Fja.dbpedia.org%2Fresource%2F%3E%0D%0APREFIX+dbpj%3A+%3Chttp%3A%2F%2Fdbpedia-dev.lodac.nii.ac.jp%2Fresource%2F%3E%0D%0APREFIX+dbo%3A+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0D%0ASELECT+distinct+%3Fplace+%3Fname+%3Faddress+%3Flat+%3Flong+%0D%0AWHERE%0D%0A%7B%0D%0A++%3Fplace+dbo%3AwikiPageWikiLink++dbpedia-ja%3A%E6%97%A5%E6%9C%AC%E3%81%AE%E6%B8%A9%E6%B3%89%E5%9C%B0%E4%B8%80%E8%A6%A7%3B%0D%0A++prop-ja%3A%E5%90%8D%E7%A7%B0+%3Fname.%0D%0A+OPTIONAL+%7B%0D%0A++%3Fplace+dbo%3Aaddress+%3Faddress.%0D%0A+%7D%0D%0A+OPTIONAL+%7B%0D%0A++%3Fplace+geo%3Alat+%3Flat.%0D%0A++%3Fplace+geo%3Along+%3Flong.%0D%0A+%7D%0D%0A%7D&format=application%2Fsparql-results%2Bjson&timeout=0&debug=on&run=+Run+Query)
- [x] 温泉地マップのvueファイルの作成
- [x] 温泉地の表示
- [x] 温泉地の緯度・経度の付近の酒蔵をMongoDBから検索して取得する
  - [x] MongoDBの酒蔵スキーマのうち、latとlngのフィールドを、coordinates:["lat", "lng"]へ変更
    - 参考：https://docs.mongodb.com/manual/geospatial-queries/
  - [x] 温泉地から、一定の距離圏内(例：5km)の酒蔵を検索する
- [x] 温泉地と酒蔵を一緒に表示する
- [x] デプロイ用データ変更方法の検討
  - locationフィールドの追加。[lng, lat]
  - locationフィールドにindexの追加。2dsphere
- [x] データ追加プログラムの検証 (テストコード準備？)

**Comment by nichesuch** [comment]
mongoに入って、以下のコマンドでロケーションデータ作成とインデックス作成を行いました。

```
db.breweries.find({latitude: {$ne: null}}).forEach(function(row){ 
    row.location = [row.longitude, row.latitude];
    db.breweries.save(row);
});

db.breweries.createIndex({location:"2dsphere"});

```

**Comment by nichesuch** [comment]
@r-soga このissueはcloseでOKですか？

**Comment by r-soga** [comment]
はい、okです。
