### ISSUE TITLE
酒蔵マップ 都道府県ごとにグループ化して表示する

### ISSUE THREAD

**Issue by nichesuch** [Code-for-SAKE/Sakepedia-Nuxt#92]
これのマーカークラスタグループを使う
https://qiita.com/Satachito/items/929a63e9b266f6db7958

**Comment by yuiseki** [comment]
FYI:
Vue-Leafletを使っているようなのでこのライブラリが使えるかもです
https://github.com/jperelli/vue2-leaflet-markercluster

**Comment by nichesuch** [comment]
グループ化する単位を都道府県ごとにできるか、もう少し調査。

**Comment by nichesuch** [comment]
一応できたけど、重なってしまう。
<img width="490" alt="スクリーンショット 2021-05-29 13 35 47" src="https://user-images.githubusercontent.com/2096703/120058019-a5826600-c082-11eb-99d3-15f223f4fe23.png">
このくらいが限界か
