### ISSUE TITLE
酒蔵追加画面の必須入力項目を「*必須」で示す

### ISSUE THREAD

**Issue by y2naranja** [Code-for-SAKE/Sakepedia-Nuxt#97]
- 要件
酒蔵追加時に、最低どの項目を入力すれば追加ができるか分からない

- 要望<br>必須項目のラベルに「*必須」を表示する

- 解決案<br>ソースを追って必須項目を洗い出してラベルを書き直すところまでやれば実現可能か

**Comment by shinjima2** [comment]
酒蔵名と都道府県のみ必須でどうでしょうか。

**Comment by y2naranja** [comment]
新規登録時は、住所から緯度経度を取得してきているので、住所も必須項目とした方が良いと思います。

**Comment by shinjima2** [comment]
酒蔵の表示順がもし読み仮名順なら、それも必須ですね

**Comment by nichesuch** [comment]
@shinjima2 ついでに他の画面の必須項目もお願いします！

**Comment by shinjima2** [comment]
日本酒、銘柄の分もプルリクしました^^

**Comment by nichesuch** [comment]
@shinjima2 ありがとうございました！
