### ISSUE TITLE
酒蔵情報の住所の頭に郵便番号を付けるか

### ISSUE THREAD

**Issue by y2naranja** [Code-for-SAKE/Sakepedia-Nuxt#99]
- 要件<br>現在登録されている酒蔵情報の住所の頭に、郵便番号があったりなかったりする
- 解決案<br>座標取得の役に立つならつける<br>邪魔になるなら取る

**Comment by y2naranja** [comment]
取るかつけるか決まったら、吉川がやります

**Comment by shinjima2** [comment]
郵便番号はない場合もありますし「郵便番号なし」で良いと思います。
住所が正しい情報であれば、郵便番号も緯度経度も逆引きできるので。

**Comment by nichesuch** [comment]
郵便番号なしで行きます！
